# Facebook - Sohan Bappy
#security:
#  oauth2:
#    client:
#      clientId: 972232863269564
#      clientSecret: 15750b42096c7ac6cd477eb6f6009a6e
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me

#GitHub- sohanbappy

#security:
#  oauth2:
#    client:
#      clientId: 37bb1d86bd9894ad5de9
#      clientSecret: 58e3a60fb25099917afc8113c56ff33820efc0c8
#      accessTokenUri: https://github.com/login/oauth/access_token
#      userAuthorizationUri: https://github.com/login/oauth/authorize
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://api.github.com/user

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 37bb1d86bd9894ad5de9
            clientSecret: 58e3a60fb25099917afc8113c56ff33820efc0c8
#github callback URL - http://localhost:8080/login/oauth2/code/github   (On APP)
          facebook:
            clientId: 972232863269564
            clientSecret: 15750b42096c7ac6cd477eb6f6009a6e
#fb

#          google:
#            clientId: -----
#            clientSecret: ------
#google